#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'
		bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

bspc config border_width 1
bspc config window_gap 15
bspc config bottom_window_gap 20
bspc config top_window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 2 > terminal/editor
bspc rule -a Termite desktop='^2' follow=on focus=on
bspc rule -a Geany desktop='^2' follow=on focus=on
bspc rule -a eDEX-UI desktop='^2' follow=on focus=on
bspc rule -a Alacritty desktop='^2' follow=on focus=on
bspc rule -a Xfce4-terminal desktop='^2' follow=on focus=on
bspc rule -a code-oss desktop='^2' follow=on focus=on
bspc rule -a Code desktop='^2' follow=on focus=on

# 1 > web
bspc rule -a Brave-browser desktop='^1' follow=on focus=on
bspc rule -a qutebrowser desktop='^1' follow=on focus=on
bspc rule -a Vivaldi-stable desktop='^1' follow=on focus=on
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a chromium desktop='^1' follow=on focus=on
bspc rule -a notion-app-enhanced desktop='^1' follow=on focus=on

# 6 > file
bspc rule -a Pcmanfm desktop='^6' follow=on focus=on
bspc rule -a Thunar desktop='^6' follow=on focus=on
bspc rule -a qBittorrent desktop='^6'

# 3 > Discord
bspc rule -a discord desktop='^3' follow=off focus=off

# 5 > MC
bspc rule -a Minecraft Launcher desktop='^5' follow=off focus=on
bspc rule -a Minecraft\ Launcher desktop='^5' follow=off focus=on
bspc rule -a Minecraft 1.8.9 desktop='^5' follow=on focus=on
bspc rule -a Minecraft\ 1.8.9 desktop='^5' follow=on focus=on
bspc rule -a org-tlauncher-tlauncher-rmo-TLauncher desktop='^5' follow=off focus=on
bspc rule -a Steam desktop='^5' follow=off focus=on
bspc rule -a GLava state=floating layer=below sticky=true locked=true border=off center=true rectangle=1919x1080+0+0
bspc rule -a Polybar state=floating layer=above
# 2 > office
declare -a office=(Geany Gucharmap Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^2' follow=on focus=on; done

# 4 > media
declare -a media=(mpv mplayer lxmusic Gimp Gimp-2.8)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done
bspc rule -a GLava desktop='^9' follow=off focus=on
bspc rule -a Rhythmbox desktop='^4' follow=on focus=on
bspc rule -a Music desktop='^4' follow=on focus=on
bspc rule -a Spotify desktop='^4' follow=on focus=on
bspc rule -a spotify desktop='^4' follow=on focus=on

# 8 > settings
bspc rule -a GParted desktop='^8' follow=on focus=on
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# 7 > videos
bspc rule -a vlc desktop='^7' follow=on focus=on
bspc rule -a Io.github.celluloid_player.Celluloid desktop='^7' follow=on focus=on
bspc rule -a Audacity desktop='^7' follow=on focus=on 

# 9 > productivity
bspc rule -a Blanket desktop='^9' follow=on focus=on
bspc rule -a pomotroid desktop='^9' follow=on focus=on 

for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# special rules
declare -a floating=(alacritty-float Pcmanfm Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a termite-float follow=on focus=on
bspc rule -a Termite follow=on focus=on
bspc rule -a alacritty-float state=floating follow=on focus=on
bspc rule -a Thunar state=floating follow=on focus=on
bspc rule -a Pcmanfm state=floating follow=on focus=on
bspc rule -a Onboard state=floating follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Geany state=floating follow=on focus=on
bspc rule -a jetbrains-webstorm state=floating follow=on focus=on
bspc rule -a jetbrains-intellij state=floating follow=on focus=on
bspc rule -a jetbrains-idea-ce state=floating follow=on focus=on
bspc rule -a jetbrains-pycharm state=floating follow=on focus=on
bspc rule -a jetbrains-toolbox state=floating follow=on focus=on
bspc rule -a Main state=floating follow=on focus=on
bspc rule -a Gnome-calculator state=floating

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager
killall Thunar

# Lauch notification daemon
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash $HOME/.fehbg

# environment
export _JAVA_AWT_WM_NONREPARENTING=1 &
wmname LD3D &

# command polybar main --config=/home/khosraw/.config/bspwm/polybar/config &

# Visualizer
exec glava &
exec sleep 5 &
exec xdo raise -N "Polybar" &

# Start mpd/tilda/discord
# exec minecraft-launcher &
# exec compton &
exec picom --experimental-backends &
exec redshift &
exec premid &
exec discord &
exec mpd &
exec unclutter -idle 10 -root &

# Start bspwm scripts
bspcolors &
bspbar &
bspfloat &

exec bspterm &
killall thunar &
